In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler , LabelEncoder
from sklearn.ensemble import ExtraTreesClassifier
from imblearn.over_sampling import RandomOverSampler

In [ ]:
# Proses melakukan import dataset yang diperlukan
test_set = pd.read_csv('/content/drive/MyDrive/DAC 1/test_feature.csv')
features = pd.read_csv('/content/drive/MyDrive/DAC 1/train_features.csv')
labels = pd.read_csv('/content/drive/MyDrive/DAC 1/train_label.csv')

# Data Preparation

In [ ]:
test_set.head()

,ID,facilities,rating,location
0,0,GymrestaurantbarInternetSwimmingPools,8.0 ExcellentFrom 1 reviews,Stokol
1,1,Poolrestaurantgyminternetbar,7.4 Very GoodFrom 22 reviews,Hallerson
2,2,BARSwimmingPoolsInternetgym,0.0 FairFrom 4 reviews,Hallerson
3,3,gymSwimmingPoolsBARintrnetRestaurant,6.8 Very GoodFrom 13 reviews,Andeman
4,4,gymRestaurantpoolbarintrnet,0.0 FairFrom 9 reviews,Hallerson

In [ ]:
features.head()

                   facilities                        rating      location
0  RestaurantBARSwimmingPools  7.8 Very GoodFrom 10 reviews        Stokol
1        intrnetRestaurantgym        5.6 GoodFrom 4 reviews  Machlessvile
2        restaurantgympoolBar  7.2 Very GoodFrom 38 reviews    Wanderland
3               BARRestaurant   7.3 Very GoodFrom 6 reviews    Uberlandia
4          InternetRestaurant  7.2 Very GoodFrom 30 reviews        Stokol

In [ ]:
labels.head()

             Price
0  13,500avg/night
1  13,000avg/night
2  19,000avg/night
3   6,000avg/night
4  20,000avg/night

# Data Train

In [ ]:
features['labels'] = labels

In [ ]:
features

,facilities,rating,location,labels
0,RestaurantBARSwimmingPools,7.8 Very GoodFrom 10 reviews,Stokol,"13,500avg/night"
1,intrnetRestaurantgym,5.6 GoodFrom 4 reviews,Machlessvile,"13,000avg/night"
2,restaurantgympoolBar,7.2 Very GoodFrom 38 reviews,Wanderland,"19,000avg/night"
3,BARRestaurant,7.3 Very GoodFrom 6 reviews,Uberlandia,"6,000avg/night"
4,InternetRestaurant,7.2 Very GoodFrom 30 reviews,Stokol,"20,000avg/night"
...,...,...,...,...
3061,barInternet,NaN,Andeman,"31,625avg/night"
3062,restaurantBarInternet,8.1 ExcellentFrom 4 reviews,Uberlandia,"30,500avg/night"
3063,Barrestaurantswimmingpools,6.7 Very GoodFrom 10 reviews,Willsmian,"14,000avg/night"
3064,Restaurant,NaN,Hallerson,"8,500avg/night"
3065,barPool,7.8 Very GoodFrom 26 reviews,Andeman,"19,000avg/night"

In [ ]:
features[['Rating', 'Description', 'Reviews']] = features['rating'].str.extract(r'([\d.]+)\s*([A-Za-z\s]+)From\s+(\d+)\s+reviews')

print(features)

                      facilities                        rating      location  \
0     RestaurantBARSwimmingPools  7.8 Very GoodFrom 10 reviews        Stokol
1           intrnetRestaurantgym        5.6 GoodFrom 4 reviews  Machlessvile
2           restaurantgympoolBar  7.2 Very GoodFrom 38 reviews    Wanderland
3                  BARRestaurant   7.3 Very GoodFrom 6 reviews    Uberlandia
4             InternetRestaurant  7.2 Very GoodFrom 30 reviews        Stokol
...                          ...                           ...           ...
3061                 barInternet                           NaN       Andeman
3062       restaurantBarInternet   8.1 ExcellentFrom 4 reviews    Uberlandia
3063  Barrestaurantswimmingpools  6.7 Very GoodFrom 10 reviews     Willsmian
3064                  Restaurant                           NaN     Hallerson
3065                     barPool  7.8 Very GoodFrom 26 reviews       Andeman

               labels Rating Description Reviews
0     13,500avg/night    7.8   Very Good      10
1     13,000avg/night    5.6        Good       4
2     19,000avg/night    7.2   Very Good      38
3      6,000avg/night    7.3   Very Good       6
4     20,000avg/night    7.2   Very Good      30
...               ...    ...         ...     ...
3061  31,625avg/night    NaN         NaN     NaN
3062  30,500avg/night    8.1   Excellent       4
3063  14,000avg/night    6.7   Very Good      10
3064   8,500avg/night    NaN         NaN     NaN
3065  19,000avg/night    7.8   Very Good      26

[3066 rows x 7 columns]

In [ ]:
features

,facilities,rating,location,labels,Rating,Description,Reviews
0,RestaurantBARSwimmingPools,7.8 Very GoodFrom 10 reviews,Stokol,"13,500avg/night",7.8,Very Good,10
1,intrnetRestaurantgym,5.6 GoodFrom 4 reviews,Machlessvile,"13,000avg/night",5.6,Good,4
2,restaurantgympoolBar,7.2 Very GoodFrom 38 reviews,Wanderland,"19,000avg/night",7.2,Very Good,38
3,BARRestaurant,7.3 Very GoodFrom 6 reviews,Uberlandia,"6,000avg/night",7.3,Very Good,6
4,InternetRestaurant,7.2 Very GoodFrom 30 reviews,Stokol,"20,000avg/night",7.2,Very Good,30
...,...,...,...,...,...,...,...
3061,barInternet,NaN,Andeman,"31,625avg/night",NaN,NaN,NaN
3062,restaurantBarInternet,8.1 ExcellentFrom 4 reviews,Uberlandia,"30,500avg/night",8.1,Excellent,4
3063,Barrestaurantswimmingpools,6.7 Very GoodFrom 10 reviews,Willsmian,"14,000avg/night",6.7,Very Good,10
3064,Restaurant,NaN,Hallerson,"8,500avg/night",NaN,NaN,NaN
3065,barPool,7.8 Very GoodFrom 26 reviews,Andeman,"19,000avg/night",7.8,Very Good,26

In [ ]:
features.drop('rating',axis=1,inplace = True)

In [ ]:
features

,facilities,location,labels,Rating,Description,Reviews
0,RestaurantBARSwimmingPools,Stokol,"13,500avg/night",7.8,Very Good,10
1,intrnetRestaurantgym,Machlessvile,"13,000avg/night",5.6,Good,4
2,restaurantgympoolBar,Wanderland,"19,000avg/night",7.2,Very Good,38
3,BARRestaurant,Uberlandia,"6,000avg/night",7.3,Very Good,6
4,InternetRestaurant,Stokol,"20,000avg/night",7.2,Very Good,30
...,...,...,...,...,...,...
3061,barInternet,Andeman,"31,625avg/night",NaN,NaN,NaN
3062,restaurantBarInternet,Uberlandia,"30,500avg/night",8.1,Excellent,4
3063,Barrestaurantswimmingpools,Willsmian,"14,000avg/night",6.7,Very Good,10
3064,Restaurant,Hallerson,"8,500avg/night",NaN,NaN,NaN
3065,barPool,Andeman,"19,000avg/night",7.8,Very Good,26

In [ ]:
features.isnull().sum()

facilities     301
location         0
labels           0
Rating         905
Description    905
Reviews        905
dtype: int64

In [ ]:
features.dropna(inplace = True)

In [ ]:
features

,facilities,location,labels,Rating,Description,Reviews
0,RestaurantBARSwimmingPools,Stokol,"13,500avg/night",7.8,Very Good,10
1,intrnetRestaurantgym,Machlessvile,"13,000avg/night",5.6,Good,4
2,restaurantgympoolBar,Wanderland,"19,000avg/night",7.2,Very Good,38
3,BARRestaurant,Uberlandia,"6,000avg/night",7.3,Very Good,6
4,InternetRestaurant,Stokol,"20,000avg/night",7.2,Very Good,30
...,...,...,...,...,...,...
3059,restaurantBAR,Andeman,"5,000avg/night",7.6,Very Good,3
3060,barrestaurantPoolGym,Andeman,"30,000avg/night",7.8,Very Good,351
3062,restaurantBarInternet,Uberlandia,"30,500avg/night",8.1,Excellent,4
3063,Barrestaurantswimmingpools,Willsmian,"14,000avg/night",6.7,Very Good,10
3065,barPool,Andeman,"19,000avg/night",7.8,Very Good,26

In [ ]:
features.isnull().sum()

facilities     0
location       0
labels         0
Rating         0
Description    0
Reviews        0
dtype: int64

In [ ]:
features.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2101 entries, 0 to 3065
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   facilities   2101 non-null   object
 1   location     2101 non-null   object
 2   labels       2101 non-null   object
 3   Rating       2101 non-null   object
 4   Description  2101 non-null   object
 5   Reviews      2101 non-null   object
dtypes: object(6)
memory usage: 114.9+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Inisialisasi objek LabelEncoder
label_encoder = LabelEncoder()

# Fit dan transformasi data features
features['Description']= label_encoder.fit_transform(features['Description'])

In [ ]:
features

,facilities,location,labels,Rating,Description,Reviews
0,RestaurantBARSwimmingPools,Stokol,"13,500avg/night",7.8,3,10
1,intrnetRestaurantgym,Machlessvile,"13,000avg/night",5.6,2,4
2,restaurantgympoolBar,Wanderland,"19,000avg/night",7.2,3,38
3,BARRestaurant,Uberlandia,"6,000avg/night",7.3,3,6
4,InternetRestaurant,Stokol,"20,000avg/night",7.2,3,30
...,...,...,...,...,...,...
3059,restaurantBAR,Andeman,"5,000avg/night",7.6,3,3
3060,barrestaurantPoolGym,Andeman,"30,000avg/night",7.8,3,351
3062,restaurantBarInternet,Uberlandia,"30,500avg/night",8.1,0,4
3063,Barrestaurantswimmingpools,Willsmian,"14,000avg/night",6.7,3,10
3065,barPool,Andeman,"19,000avg/night",7.8,3,26

In [ ]:
features['labels'] = features['labels'].str.replace('avg/night',"")

print(features)

                      facilities      location  labels Rating  Description  \
0     RestaurantBARSwimmingPools        Stokol  13,500    7.8            3
1           intrnetRestaurantgym  Machlessvile  13,000    5.6            2
2           restaurantgympoolBar    Wanderland  19,000    7.2            3
3                  BARRestaurant    Uberlandia   6,000    7.3            3
4             InternetRestaurant        Stokol  20,000    7.2            3
...                          ...           ...     ...    ...          ...
3059               restaurantBAR       Andeman   5,000    7.6            3
3060        barrestaurantPoolGym       Andeman  30,000    7.8            3
3062       restaurantBarInternet    Uberlandia  30,500    8.1            0
3063  Barrestaurantswimmingpools     Willsmian  14,000    6.7            3
3065                     barPool       Andeman  19,000    7.8            3

     Reviews
0         10
1          4
2         38
3          6
4         30
...      ...
3059       3
3060     351
3062       4
3063      10
3065      26

[2101 rows x 6 columns]

In [ ]:
features

,facilities,location,labels,Rating,Description,Reviews
0,RestaurantBARSwimmingPools,Stokol,"13,500",7.8,3,10
1,intrnetRestaurantgym,Machlessvile,"13,000",5.6,2,4
2,restaurantgympoolBar,Wanderland,"19,000",7.2,3,38
3,BARRestaurant,Uberlandia,"6,000",7.3,3,6
4,InternetRestaurant,Stokol,"20,000",7.2,3,30
...,...,...,...,...,...,...
3059,restaurantBAR,Andeman,"5,000",7.6,3,3
3060,barrestaurantPoolGym,Andeman,"30,000",7.8,3,351
3062,restaurantBarInternet,Uberlandia,"30,500",8.1,0,4
3063,Barrestaurantswimmingpools,Willsmian,"14,000",6.7,3,10
3065,barPool,Andeman,"19,000",7.8,3,26

In [ ]:
features['labels'] = features['labels'].str.replace(',',"")

print(features)

                      facilities      location labels Rating  Description  \
0     RestaurantBARSwimmingPools        Stokol  13500    7.8            3
1           intrnetRestaurantgym  Machlessvile  13000    5.6            2
2           restaurantgympoolBar    Wanderland  19000    7.2            3
3                  BARRestaurant    Uberlandia   6000    7.3            3
4             InternetRestaurant        Stokol  20000    7.2            3
...                          ...           ...    ...    ...          ...
3059               restaurantBAR       Andeman   5000    7.6            3
3060        barrestaurantPoolGym       Andeman  30000    7.8            3
3062       restaurantBarInternet    Uberlandia  30500    8.1            0
3063  Barrestaurantswimmingpools     Willsmian  14000    6.7            3
3065                     barPool       Andeman  19000    7.8            3

     Reviews
0         10
1          4
2         38
3          6
4         30
...      ...
3059       3
3060     351
3062       4
3063      10
3065      26

[2101 rows x 6 columns]

In [ ]:
features['labels'] = features['labels'].astype(int)
features['Reviews'] = features['Reviews'].astype(int)
features['Rating'] = features['Rating'].astype(float)

In [ ]:
features.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2101 entries, 0 to 3065
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   facilities   2101 non-null   object
 1   location     2101 non-null   object
 2   labels       2101 non-null   int64
 3   Rating       2101 non-null   float64
 4   Description  2101 non-null   int64
 5   Reviews      2101 non-null   int64
dtypes: float64(1), int64(3), object(2)
memory usage: 114.9+ KB

In [ ]:
features.to_csv("Percobaan Train 1.csv",index = False)

# Data Preparation

In [ ]:
test_set.head()

,ID,facilities,rating,location
0,0,GymrestaurantbarInternetSwimmingPools,8.0 ExcellentFrom 1 reviews,Stokol
1,1,Poolrestaurantgyminternetbar,7.4 Very GoodFrom 22 reviews,Hallerson
2,2,BARSwimmingPoolsInternetgym,0.0 FairFrom 4 reviews,Hallerson
3,3,gymSwimmingPoolsBARintrnetRestaurant,6.8 Very GoodFrom 13 reviews,Andeman
4,4,gymRestaurantpoolbarintrnet,0.0 FairFrom 9 reviews,Hallerson

# Data Test

In [ ]:
test_set[['Rating', 'Description', 'Reviews']] = test_set['rating'].str.extract(r'([\d.]+)\s*([A-Za-z\s]+)From\s+(\d+)\s+reviews')

print(test_set)

      ID                             facilities                        rating  \
0      0  GymrestaurantbarInternetSwimmingPools   8.0 ExcellentFrom 1 reviews
1      1           Poolrestaurantgyminternetbar  7.4 Very GoodFrom 22 reviews
2      2            BARSwimmingPoolsInternetgym        0.0 FairFrom 4 reviews
3      3   gymSwimmingPoolsBARintrnetRestaurant  6.8 Very GoodFrom 13 reviews
4      4            gymRestaurantpoolbarintrnet        0.0 FairFrom 9 reviews
..   ...                                    ...                           ...
762  762                   BARPoolRestaurantGym   8.1 ExcellentFrom 9 reviews
763  763            intrnetGympoolrestaurantBar   8.0 ExcellentFrom 4 reviews
764  764   RestaurantgymintrnetBARswimmingpools  7.4 Very GoodFrom 19 reviews
765  765           gymInternetBarpoolRestaurant  9.0 ExcellentFrom 17 reviews
766  766           RestaurantGyminternetpoolBAR  6.9 Very GoodFrom 21 reviews

       location Rating Description Reviews
0        Stokol    8.0   Excellent       1
1     Hallerson    7.4   Very Good      22
2     Hallerson    0.0        Fair       4
3       Andeman    6.8   Very Good      13
4     Hallerson    0.0        Fair       9
..          ...    ...         ...     ...
762     Andeman    8.1   Excellent       9
763  Wanderland    8.0   Excellent       4
764     Andeman    7.4   Very Good      19
765   Hallerson    9.0   Excellent      17
766  Uberlandia    6.9   Very Good      21

[767 rows x 7 columns]

In [ ]:
test_set

,ID,facilities,rating,location,Rating,Description,Reviews
0,0,GymrestaurantbarInternetSwimmingPools,8.0 ExcellentFrom 1 reviews,Stokol,8.0,Excellent,1
1,1,Poolrestaurantgyminternetbar,7.4 Very GoodFrom 22 reviews,Hallerson,7.4,Very Good,22
2,2,BARSwimmingPoolsInternetgym,0.0 FairFrom 4 reviews,Hallerson,0.0,Fair,4
3,3,gymSwimmingPoolsBARintrnetRestaurant,6.8 Very GoodFrom 13 reviews,Andeman,6.8,Very Good,13
4,4,gymRestaurantpoolbarintrnet,0.0 FairFrom 9 reviews,Hallerson,0.0,Fair,9
...,...,...,...,...,...,...,...
762,762,BARPoolRestaurantGym,8.1 ExcellentFrom 9 reviews,Andeman,8.1,Excellent,9
763,763,intrnetGympoolrestaurantBar,8.0 ExcellentFrom 4 reviews,Wanderland,8.0,Excellent,4
764,764,RestaurantgymintrnetBARswimmingpools,7.4 Very GoodFrom 19 reviews,Andeman,7.4,Very Good,19
765,765,gymInternetBarpoolRestaurant,9.0 ExcellentFrom 17 reviews,Hallerson,9.0,Excellent,17
766,766,RestaurantGyminternetpoolBAR,6.9 Very GoodFrom 21 reviews,Uberlandia,6.9,Very Good,21

In [ ]:
test_set.drop('rating',axis=1,inplace = True)

In [ ]:
test_set

,ID,facilities,location,Rating,Description,Reviews
0,0,GymrestaurantbarInternetSwimmingPools,Stokol,8.0,Excellent,1
1,1,Poolrestaurantgyminternetbar,Hallerson,7.4,Very Good,22
2,2,BARSwimmingPoolsInternetgym,Hallerson,0.0,Fair,4
3,3,gymSwimmingPoolsBARintrnetRestaurant,Andeman,6.8,Very Good,13
4,4,gymRestaurantpoolbarintrnet,Hallerson,0.0,Fair,9
...,...,...,...,...,...,...
762,762,BARPoolRestaurantGym,Andeman,8.1,Excellent,9
763,763,intrnetGympoolrestaurantBar,Wanderland,8.0,Excellent,4
764,764,RestaurantgymintrnetBARswimmingpools,Andeman,7.4,Very Good,19
765,765,gymInternetBarpoolRestaurant,Hallerson,9.0,Excellent,17
766,766,RestaurantGyminternetpoolBAR,Uberlandia,6.9,Very Good,21

In [ ]:
test_set.isnull().sum()

ID             0
facilities     0
location       0
Rating         0
Description    0
Reviews        0
dtype: int64

In [ ]:
test_set

,ID,facilities,location,Rating,Description,Reviews
0,0,GymrestaurantbarInternetSwimmingPools,Stokol,8.0,Excellent,1
1,1,Poolrestaurantgyminternetbar,Hallerson,7.4,Very Good,22
2,2,BARSwimmingPoolsInternetgym,Hallerson,0.0,Fair,4
3,3,gymSwimmingPoolsBARintrnetRestaurant,Andeman,6.8,Very Good,13
4,4,gymRestaurantpoolbarintrnet,Hallerson,0.0,Fair,9
...,...,...,...,...,...,...
762,762,BARPoolRestaurantGym,Andeman,8.1,Excellent,9
763,763,intrnetGympoolrestaurantBar,Wanderland,8.0,Excellent,4
764,764,RestaurantgymintrnetBARswimmingpools,Andeman,7.4,Very Good,19
765,765,gymInternetBarpoolRestaurant,Hallerson,9.0,Excellent,17
766,766,RestaurantGyminternetpoolBAR,Uberlandia,6.9,Very Good,21

In [ ]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           767 non-null    int64
 1   facilities   767 non-null    object
 2   location     767 non-null    object
 3   Rating       767 non-null    object
 4   Description  767 non-null    object
 5   Reviews      767 non-null    object
dtypes: int64(1), object(5)
memory usage: 36.1+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Inisialisasi objek LabelEncoder
label_encoder = LabelEncoder()

# Fit dan transformasi data features
test_set['Description']= label_encoder.fit_transform(test_set['Description'])

In [ ]:
test_set

,ID,facilities,location,Rating,Description,Reviews
0,0,GymrestaurantbarInternetSwimmingPools,Stokol,8.0,0,1
1,1,Poolrestaurantgyminternetbar,Hallerson,7.4,3,22
2,2,BARSwimmingPoolsInternetgym,Hallerson,0.0,1,4
3,3,gymSwimmingPoolsBARintrnetRestaurant,Andeman,6.8,3,13
4,4,gymRestaurantpoolbarintrnet,Hallerson,0.0,1,9
...,...,...,...,...,...,...
762,762,BARPoolRestaurantGym,Andeman,8.1,0,9
763,763,intrnetGympoolrestaurantBar,Wanderland,8.0,0,4
764,764,RestaurantgymintrnetBARswimmingpools,Andeman,7.4,3,19
765,765,gymInternetBarpoolRestaurant,Hallerson,9.0,0,17
766,766,RestaurantGyminternetpoolBAR,Uberlandia,6.9,3,21

In [ ]:
test_set['Reviews'] = test_set['Reviews'].astype(int)
test_set['Rating'] = test_set['Rating'].astype(float)

In [ ]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           767 non-null    int64
 1   facilities   767 non-null    object
 2   location     767 non-null    object
 3   Rating       767 non-null    float64
 4   Description  767 non-null    int64
 5   Reviews      767 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 36.1+ KB

In [ ]:
test_set.to_csv("Percobaan Test 2.csv",index = False)

# Modeling

In [ ]:
x_unixversal = features[['Rating','Description','Reviews']]
y_unixversal = features[['labels']]

x_pred_unixversal = test_set[['Rating', 'Description', 'Reviews']]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_unixversal, y_unixversal, test_size= 0.2)
print('x_train', x_train.shape)
print('x_test', x_test.shape)
print('y_train', y_train.shape)
print('y_test', y_test.shape)
print('x_pred', x_pred_unixversal.shape)

x_train (1680, 3)
x_test (421, 3)
y_train (1680, 1)
y_test (421, 1)
x_pred (767, 3)

In [ ]:
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Skala data menggunakan StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Inisialisasi model SVR
model = SVR(kernel='linear')

# Melatih model
model.fit(x_train, y_train)

# Melakukan prediksi pada data uji
y_pred = model.predict(x_test)

# Menghitung mean squared error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Squared Error:", mae)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Mean Squared Error: 10688.082158930576

# KNN

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.neighbors import KNeighborsRegressor


knn = KNeighborsRegressor(5, metric="euclidean")
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

mse = mean_squared_error(y_pred, y_test)
mae = mean_absolute_error(y_pred, y_test)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error: {}".format(mse))
print("Mean Absolute Error: {}".format(mae))
print("Root Mean Absolute Error: {}".format(rmse))
print("R2 score: {}".format(r2))

Mean Squared Error: 48370388.61995249
Mean Absolute Error: 3319.4171021377674
Root Mean Absolute Error: 6954.882358455281
R2 score: 0.831852613416173

In [ ]:
prediction_dictionaries = {'KNN-Default': y_pred}

In [ ]:
prediction_list = pd.DataFrame({'Actual Values': np.array(y_test).flatten(), 'KNN-Default': y_pred.flatten()}).head(20)
prediction_list.set_index('Actual Values', inplace=True)
prediction_list

               KNN-Default
Actual Values
8000                7700.0
25000              25000.0
11500              11500.0
12500              12500.0
11000              11000.0
30000              30000.0
13975              13975.0
27000              27000.0
12000              12000.0
5000               10400.0
10000               4700.0
3000                3000.0
20000              20000.0
30000              16593.2
56000              37200.0
67000              67000.0
20000              15800.0
9000                5600.0
17200              12880.0
20000              21600.0

In [ ]:
error_dict = {'KNN Default': [mae, r2]}
error_list = pd.DataFrame()
error_list['KNN Default'] = [mae, r2]
error_list.reset_index(inplace=True, drop=True)
#error_list.rename(columns={0: 'MSE KNN Default'}, inplace=True)
error_list.index =['Mean Absolute Error', 'R2 Score']
error_list.T

             Mean Absolute Error  R2 Score
KNN Default          3319.417102  0.831853

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid = {'p': [1, 2],
              'n_neighbors' : [ 5, 10, 15]
              }

grid_knn = GridSearchCV(KNeighborsRegressor(n_jobs=-1), param_grid, refit = True, verbose = 10, n_jobs=-1, cv=5,scoring="neg_mean_squared_error")

grid_knn.fit(x_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(cv=5, estimator=KNeighborsRegressor(n_jobs=-1), n_jobs=-1,
             param_grid={'n_neighbors': [5, 10, 15], 'p': [1, 2]},
             scoring='neg_mean_squared_error', verbose=10)

In [ ]:
print(f"Best parameters are {grid_knn.best_params_}")
print("Best score is {}".format(grid_knn.best_score_ * -1))
print("Best model is {}".format(grid_knn.best_estimator_))
#print("The score for hyperparameter tuning are {}".format(grid.cv_results_))

Best parameters are {'n_neighbors': 5, 'p': 1}
Best score is 64851143.724952385
Best model is KNeighborsRegressor(n_jobs=-1, p=1)

In [ ]:
knr_best = KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=5, p=1,
                    weights='uniform')
knr_best.fit(x_train, y_train)
y_pred_best = knr_best.predict(x_test)

mse_knn_best = mean_squared_error(y_pred_best, y_test)
mae_knn_best = mean_absolute_error(y_pred, y_test)
rmse_knn_best = np.sqrt(mse)
r2_knn_best = r2_score(y_test, y_pred_best)

print("Mean Squared Error: {}".format(mse_knn_best))
print("Mean Absolute Error: {}".format(mae_knn_best))
print("Root Mean Absolute Error: {}".format(rmse_knn_best))
print("R2 score: {}".format(r2_knn_best))

Mean Squared Error: 48995946.814726844
Mean Absolute Error: 3319.4171021377674
Root Mean Absolute Error: 6954.882358455281
R2 score: 0.8296780190288124

In [ ]:
prediction_dictionaries['Knn-Best'] = y_pred_best

In [ ]:
prediction_list['KNN-Best'] = y_pred_best[:20]
prediction_list

               KNN-Default  KNN-Best
Actual Values
8000                7700.0    7700.0
25000              25000.0   25000.0
11500              11500.0   11500.0
12500              12500.0   12500.0
11000              11000.0   11000.0
30000              30000.0   30000.0
13975              13975.0   13975.0
27000              27000.0   27000.0
12000              12000.0   12000.0
5000               10400.0   10400.0
10000               4700.0    4700.0
3000                3000.0    3000.0
20000              20000.0   20000.0
30000              16593.2   16593.2
56000              37200.0   37200.0
67000              67000.0   67000.0
20000              15800.0   15800.0
9000                5600.0    5600.0
17200              12880.0   12880.0
20000              21600.0   21600.0

In [ ]:
error_list['MSE KNN-Best'] = [mae_knn_best, r2_knn_best]
error_list.T

              Mean Absolute Error  R2 Score
KNN Default           3319.417102  0.831853
MSE KNN-Best          3319.417102  0.829678

In [ ]:
y_pred_best.shape

(421, 1)

# Submission 1

In [ ]:
submission = pd.read_csv("/content/drive/MyDrive/DAC 1/submission_format.csv")

In [ ]:
knr_best = KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=5, p=1,
                    weights='uniform')
knr_best.fit(x_train, y_train)
y_pred_best = knr_best.predict(x_pred_unixversal)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsRegressor was fitted without feature names
  warnings.warn(

In [ ]:
submission['Price'] = y_pred_best

In [ ]:
submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      767 non-null    int64
 1   Price   767 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 12.1 KB

In [ ]:
submission

      ID    Price
0      0  22300.0
1      1  30000.0
2      2  20000.0
3      3  30000.0
4      4  30000.0
..   ...      ...
762  762  30000.0
763  763  20000.0
764  764  30000.0
765  765  30000.0
766  766  30000.0

[767 rows x 2 columns]

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn import tree
from sklearn import metrics

forest_model = RandomForestRegressor(random_state=42) #n_estimators is 100 by default
forest_model.fit(x_train, y_train)
forest_model_prediction = forest_model.predict(x_test)

forest_mse = metrics.mean_squared_error(y_test, forest_model_prediction)
forest_mae = metrics.mean_absolute_error(y_test, forest_model_prediction)
forest_rmse = np.sqrt(forest_mse)
forest_r2 = metrics.r2_score(y_test, forest_model_prediction)

print("Mean Squared Error: {}".format(forest_mse))
print("Mean Absolute Error: {}".format(forest_mae))
print("Root Mean Absolute Error: {}".format(forest_rmse))
print("R2 score: {}".format(forest_r2))

<ipython-input-161-335a678ea313>:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest_model.fit(x_train, y_train)

Mean Squared Error: 32736486.811779626
Mean Absolute Error: 2199.9059958256066
Root Mean Absolute Error: 5721.580796578829
R2 score: 0.8861999074147181

In [ ]:
prediction_list['Random Forest - Default'] = np.array(forest_model_prediction[:20])
prediction_list

               KNN-Default  KNN-Best  Random Forest - Default
Actual Values
8000                7700.0    7700.0              7614.795177
25000              25000.0   25000.0             25000.000000
11500              11500.0   11500.0             11500.000000
12500              12500.0   12500.0             12500.000000
11000              11000.0   11000.0             11000.000000
30000              30000.0   30000.0             30000.000000
13975              13975.0   13975.0             13975.000000
27000              27000.0   27000.0             27000.000000
12000              12000.0   12000.0             12000.000000
5000               10400.0   10400.0              6061.759048
10000               4700.0    4700.0             18072.500000
3000                3000.0    3000.0              3010.000000
20000              20000.0   20000.0             20000.000000
30000              16593.2   16593.2             25550.110000
56000              37200.0   37200.0             39743.025431
67000              67000.0   67000.0             66457.500000
20000              15800.0   15800.0             20549.040616
9000                5600.0    5600.0              5380.955156
17200              12880.0   12880.0             17817.825758
20000              21600.0   21600.0             19800.000000

In [ ]:
error_list['Random Forest - Default'] = [forest_mae, forest_r2]
error_list.T

                         Mean Absolute Error  R2 Score
KNN Default                      3319.417102  0.831853
MSE KNN-Best                     3319.417102  0.829678
Random Forest - Default          2199.905996  0.886200

In [ ]:
forest_model = RandomForestRegressor(random_state=42) #n_estimators is 100 by default

# Definisikan grid parameter yang ingin ditelusuri
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10]
}

# Inisialisasi GridSearchCV dengan model dan grid parameter
grid_search = GridSearchCV(forest_model, param_grid, cv=5, scoring='neg_mean_squared_error')

# Melatih model dengan melakukan penalaan hiperparameter
grid_search.fit(x_train, y_train)

# Menampilkan kombinasi terbaik dari hiperparameter
print("Kombinasi Terbaik:", grid_search.best_params_)

# Melakukan prediksi pada data uji dengan model terbaik
y_pred = grid_search.predict(x_test)

# Menghitung mean squared error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Squared Error:", mae)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

Kombinasi Terbaik: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 50}
Mean Squared Error: 2238.2041450531055

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Skala data menggunakan StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

# Definisikan parameter model XGBoost
params = {
    'objective': 'reg:squarederror',
    'colsample_bytree': 0.8,
    'learning_rate': 0.1,
    'max_depth': 5,
    'alpha': 10
}

# Latih model XGBoost
model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)
model.fit(x_train,y_train)

# Lakukan prediksi pada data uji
y_pred = model.predict(x_test)

# Menghitung mean absolute error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 2266.3394065005195

In [ ]:
pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting catboost
  Downloading catboost-1.2-cp310-cp310-manylinux2014_x86_64.whl (98.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 3.0 MB/s eta 0:00:00
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.22.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.13.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2022.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.2)
Installing collected packages: catboost
Successfully installed catboost-1.2

In [ ]:
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Skala data menggunakan StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Inisialisasi model CatBoost Regressor
model = CatBoostRegressor(random_state=42)

# Melatih model
model.fit(x_train, y_train)

# Melakukan prediksi pada data uji
y_pred = model.predict(x_test)

# Menghitung mean squared error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Squared Error:", mae)

Learning rate set to 0.04444
0:	learn: 17919.7947653	total: 50ms	remaining: 50s
1:	learn: 17816.7565327	total: 50.7ms	remaining: 25.3s
2:	learn: 17737.4680438	total: 53.4ms	remaining: 17.8s
3:	learn: 17635.7985562	total: 54.5ms	remaining: 13.6s
4:	learn: 17530.3748531	total: 56.3ms	remaining: 11.2s
5:	learn: 17397.6216408	total: 58ms	remaining: 9.62s
6:	learn: 17334.2353084	total: 64.8ms	remaining: 9.19s
7:	learn: 17306.3989940	total: 66.1ms	remaining: 8.2s
8:	learn: 17240.4102675	total: 67.7ms	remaining: 7.46s
9:	learn: 17111.8695234	total: 70.7ms	remaining: 7s
10:	learn: 17057.3855214	total: 75ms	remaining: 6.74s
11:	learn: 16961.4104086	total: 77.1ms	remaining: 6.35s
12:	learn: 16899.1976764	total: 79.3ms	remaining: 6.02s
13:	learn: 16857.7120375	total: 85.2ms	remaining: 6s
14:	learn: 16813.3257914	total: 88.2ms	remaining: 5.79s
15:	learn: 16762.4401170	total: 90.1ms	remaining: 5.54s
16:	learn: 16686.3446945	total: 95.5ms	remaining: 5.52s
17:	learn: 16618.2496164	total: 101ms	remaining: 5.51s
18:	learn: 16558.8340528	total: 104ms	remaining: 5.35s
19:	learn: 16501.9248436	total: 106ms	remaining: 5.17s
20:	learn: 16454.7115710	total: 108ms	remaining: 5.03s
21:	learn: 16403.9360469	total: 111ms	remaining: 4.94s
22:	learn: 16378.6374197	total: 125ms	remaining: 5.3s
23:	learn: 16289.3329319	total: 128ms	remaining: 5.22s
24:	learn: 16254.5017655	total: 143ms	remaining: 5.59s
25:	learn: 16216.3699583	total: 152ms	remaining: 5.71s
26:	learn: 16168.7208951	total: 155ms	remaining: 5.58s
27:	learn: 16117.2350756	total: 157ms	remaining: 5.44s
28:	learn: 16063.2469156	total: 158ms	remaining: 5.3s
29:	learn: 16022.6059681	total: 164ms	remaining: 5.3s
30:	learn: 15971.6751647	total: 182ms	remaining: 5.68s
31:	learn: 15947.3206660	total: 184ms	remaining: 5.57s
32:	learn: 15927.0755803	total: 190ms	remaining: 5.56s
33:	learn: 15881.3893548	total: 192ms	remaining: 5.45s
34:	learn: 15850.0502499	total: 197ms	remaining: 5.42s
35:	learn: 15807.0950732	total: 201ms	remaining: 5.38s
36:	learn: 15789.9044215	total: 203ms	remaining: 5.29s
37:	learn: 15763.3589283	total: 208ms	remaining: 5.26s
38:	learn: 15743.4421001	total: 219ms	remaining: 5.4s
39:	learn: 15672.9833235	total: 223ms	remaining: 5.34s
40:	learn: 15626.8895473	total: 227ms	remaining: 5.31s
41:	learn: 15623.2022193	total: 232ms	remaining: 5.3s
42:	learn: 15591.7865670	total: 239ms	remaining: 5.32s
43:	learn: 15539.1153033	total: 241ms	remaining: 5.24s
44:	learn: 15511.4169878	total: 244ms	remaining: 5.17s
45:	learn: 15450.1762591	total: 245ms	remaining: 5.09s
46:	learn: 15415.3314085	total: 253ms	remaining: 5.14s
47:	learn: 15382.6853773	total: 260ms	remaining: 5.15s
48:	learn: 15298.6622610	total: 271ms	remaining: 5.25s
49:	learn: 15271.5215704	total: 279ms	remaining: 5.31s
50:	learn: 15233.0328466	total: 284ms	remaining: 5.28s
51:	learn: 15212.5696333	total: 294ms	remaining: 5.35s
52:	learn: 15196.3566108	total: 297ms	remaining: 5.31s
53:	learn: 15159.7934388	total: 299ms	remaining: 5.23s
54:	learn: 15127.5305689	total: 301ms	remaining: 5.16s
55:	learn: 15062.5742023	total: 303ms	remaining: 5.1s
56:	learn: 14989.0235619	total: 304ms	remaining: 5.03s
57:	learn: 14942.0431195	total: 306ms	remaining: 4.97s
58:	learn: 14895.6028928	total: 309ms	remaining: 4.92s
59:	learn: 14855.4524459	total: 311ms	remaining: 4.87s
60:	learn: 14815.7244809	total: 318ms	remaining: 4.89s
61:	learn: 14790.1322544	total: 324ms	remaining: 4.9s
62:	learn: 14761.3882366	total: 327ms	remaining: 4.86s
63:	learn: 14725.1470022	total: 336ms	remaining: 4.92s
64:	learn: 14673.6271605	total: 338ms	remaining: 4.86s
65:	learn: 14658.7650113	total: 352ms	remaining: 4.98s
66:	learn: 14637.1064420	total: 353ms	remaining: 4.91s
67:	learn: 14604.7828870	total: 354ms	remaining: 4.85s
68:	learn: 14570.5414749	total: 363ms	remaining: 4.9s
69:	learn: 14549.9247964	total: 369ms	remaining: 4.91s
70:	learn: 14492.6421990	total: 370ms	remaining: 4.84s
71:	learn: 14470.1511706	total: 381ms	remaining: 4.92s
72:	learn: 14433.4400956	total: 383ms	remaining: 4.86s
73:	learn: 14417.8516530	total: 384ms	remaining: 4.8s
74:	learn: 14410.6880711	total: 384ms	remaining: 4.74s
75:	learn: 14394.1354028	total: 391ms	remaining: 4.76s
76:	learn: 14376.3347590	total: 396ms	remaining: 4.75s
77:	learn: 14348.4612088	total: 408ms	remaining: 4.83s
78:	learn: 14327.5369927	total: 410ms	remaining: 4.78s
79:	learn: 14307.9279546	total: 411ms	remaining: 4.73s
80:	learn: 14293.0421614	total: 414ms	remaining: 4.7s
81:	learn: 14242.7367515	total: 416ms	remaining: 4.66s
82:	learn: 14220.8245338	total: 420ms	remaining: 4.64s
83:	learn: 14192.2656715	total: 422ms	remaining: 4.6s
84:	learn: 14166.3523369	total: 424ms	remaining: 4.57s
85:	learn: 14154.4866047	total: 427ms	remaining: 4.54s
86:	learn: 14127.5026189	total: 429ms	remaining: 4.5s
87:	learn: 14103.8073484	total: 432ms	remaining: 4.47s
88:	learn: 14101.5485330	total: 434ms	remaining: 4.45s
89:	learn: 14090.5444763	total: 436ms	remaining: 4.41s
90:	learn: 14034.7537739	total: 443ms	remaining: 4.42s
91:	learn: 13997.1671066	total: 445ms	remaining: 4.39s
92:	learn: 13977.7434633	total: 448ms	remaining: 4.37s
93:	learn: 13960.3808973	total: 453ms	remaining: 4.37s
94:	learn: 13910.1051520	total: 455ms	remaining: 4.33s
95:	learn: 13887.8515737	total: 457ms	remaining: 4.3s
96:	learn: 13856.9528753	total: 459ms	remaining: 4.28s
97:	learn: 13846.0075895	total: 461ms	remaining: 4.24s
98:	learn: 13813.2110747	total: 465ms	remaining: 4.23s
99:	learn: 13756.7174489	total: 469ms	remaining: 4.22s
100:	learn: 13730.1483510	total: 475ms	remaining: 4.22s
101:	learn: 13709.2575404	total: 477ms	remaining: 4.2s
102:	learn: 13695.5276660	total: 484ms	remaining: 4.22s
103:	learn: 13687.4619712	total: 489ms	remaining: 4.21s
104:	learn: 13650.0871458	total: 494ms	remaining: 4.21s
105:	learn: 13629.8111425	total: 499ms	remaining: 4.21s
106:	learn: 13589.9174610	total: 501ms	remaining: 4.18s
107:	learn: 13578.8300156	total: 502ms	remaining: 4.15s
108:	learn: 13572.0980192	total: 504ms	remaining: 4.12s
109:	learn: 13567.1629103	total: 513ms	remaining: 4.15s
110:	learn: 13535.1222322	total: 516ms	remaining: 4.13s
111:	learn: 13514.6460877	total: 520ms	remaining: 4.12s
112:	learn: 13489.5745756	total: 522ms	remaining: 4.1s
113:	learn: 13482.5720221	total: 524ms	remaining: 4.07s
114:	learn: 13459.7106642	total: 526ms	remaining: 4.05s
115:	learn: 13435.0508240	total: 528ms	remaining: 4.02s
116:	learn: 13399.4261788	total: 530ms	remaining: 4s
117:	learn: 13384.7873169	total: 531ms	remaining: 3.97s
118:	learn: 13324.6445362	total: 533ms	remaining: 3.95s
119:	learn: 13312.2281093	total: 535ms	remaining: 3.92s
120:	learn: 13275.2719845	total: 536ms	remaining: 3.89s
121:	learn: 13246.4270790	total: 538ms	remaining: 3.87s
122:	learn: 13228.1395147	total: 540ms	remaining: 3.85s
123:	learn: 13224.6944687	total: 542ms	remaining: 3.83s
124:	learn: 13203.0619796	total: 543ms	remaining: 3.8s
125:	learn: 13200.8342527	total: 545ms	remaining: 3.78s
126:	learn: 13151.7457122	total: 546ms	remaining: 3.75s
127:	learn: 13130.2791758	total: 548ms	remaining: 3.73s
128:	learn: 13122.8355290	total: 550ms	remaining: 3.71s
129:	learn: 13104.5423823	total: 552ms	remaining: 3.69s
130:	learn: 13091.8420503	total: 554ms	remaining: 3.67s
131:	learn: 13057.8324573	total: 556ms	remaining: 3.66s
132:	learn: 13054.9405113	total: 558ms	remaining: 3.64s
133:	learn: 13035.1884897	total: 569ms	remaining: 3.68s
134:	learn: 13018.6885442	total: 582ms	remaining: 3.73s
135:	learn: 12974.4419373	total: 584ms	remaining: 3.71s
136:	learn: 12973.9044186	total: 590ms	remaining: 3.72s
137:	learn: 12955.8830607	total: 592ms	remaining: 3.69s
138:	learn: 12924.5467614	total: 594ms	remaining: 3.68s
139:	learn: 12902.1362572	total: 596ms	remaining: 3.66s
140:	learn: 12883.1129875	total: 599ms	remaining: 3.65s
141:	learn: 12867.3585720	total: 601ms	remaining: 3.63s
142:	learn: 12865.4114307	total: 602ms	remaining: 3.61s
143:	learn: 12813.7112497	total: 604ms	remaining: 3.59s
144:	learn: 12800.2985204	total: 607ms	remaining: 3.58s
145:	learn: 12789.6438850	total: 608ms	remaining: 3.56s
146:	learn: 12774.2528461	total: 610ms	remaining: 3.54s
147:	learn: 12763.1680391	total: 612ms	remaining: 3.52s
148:	learn: 12749.2294802	total: 614ms	remaining: 3.51s
149:	learn: 12727.8903137	total: 616ms	remaining: 3.49s
150:	learn: 12694.3643437	total: 618ms	remaining: 3.48s
151:	learn: 12673.8565062	total: 620ms	remaining: 3.46s
152:	learn: 12659.0718606	total: 623ms	remaining: 3.45s
153:	learn: 12618.1010312	total: 625ms	remaining: 3.43s
154:	learn: 12604.9465804	total: 627ms	remaining: 3.42s
155:	learn: 12578.7998398	total: 628ms	remaining: 3.4s
156:	learn: 12535.4198556	total: 633ms	remaining: 3.4s
157:	learn: 12521.9112251	total: 635ms	remaining: 3.38s
158:	learn: 12521.1800477	total: 636ms	remaining: 3.37s
159:	learn: 12501.3159609	total: 646ms	remaining: 3.39s
160:	learn: 12494.6763014	total: 648ms	remaining: 3.38s
161:	learn: 12466.3270088	total: 650ms	remaining: 3.36s
162:	learn: 12431.4087399	total: 659ms	remaining: 3.38s
163:	learn: 12414.6657955	total: 670ms	remaining: 3.41s
164:	learn: 12375.0390285	total: 671ms	remaining: 3.4s
165:	learn: 12353.5971139	total: 672ms	remaining: 3.38s
166:	learn: 12322.1428402	total: 673ms	remaining: 3.36s
167:	learn: 12316.0933410	total: 674ms	remaining: 3.34s
168:	learn: 12296.3298617	total: 679ms	remaining: 3.34s
169:	learn: 12284.6700363	total: 680ms	remaining: 3.32s
170:	learn: 12271.5058258	total: 680ms	remaining: 3.3s
171:	learn: 12251.1825444	total: 681ms	remaining: 3.28s
172:	learn: 12247.2908246	total: 681ms	remaining: 3.26s
173:	learn: 12220.3636549	total: 686ms	remaining: 3.26s
174:	learn: 12178.7260424	total: 687ms	remaining: 3.24s
175:	learn: 12154.8288013	total: 688ms	remaining: 3.22s
176:	learn: 12137.3269262	total: 688ms	remaining: 3.2s
177:	learn: 12101.2854948	total: 689ms	remaining: 3.18s
178:	learn: 12081.9673841	total: 689ms	remaining: 3.16s
179:	learn: 12038.8353030	total: 690ms	remaining: 3.14s
180:	learn: 12017.2396494	total: 690ms	remaining: 3.12s
181:	learn: 11999.0197144	total: 691ms	remaining: 3.1s
182:	learn: 11963.4577365	total: 692ms	remaining: 3.09s
183:	learn: 11947.6500280	total: 692ms	remaining: 3.07s
184:	learn: 11932.6778207	total: 693ms	remaining: 3.05s
185:	learn: 11909.2275187	total: 694ms	remaining: 3.04s
186:	learn: 11891.7470745	total: 699ms	remaining: 3.04s
187:	learn: 11864.2713916	total: 700ms	remaining: 3.02s
188:	learn: 11843.5988868	total: 701ms	remaining: 3.01s
189:	learn: 11830.9092367	total: 701ms	remaining: 2.99s
190:	learn: 11784.7209380	total: 702ms	remaining: 2.97s
191:	learn: 11772.2908371	total: 703ms	remaining: 2.96s
192:	learn: 11746.5812793	total: 703ms	remaining: 2.94s
193:	learn: 11729.1218341	total: 704ms	remaining: 2.92s
194:	learn: 11702.8102748	total: 705ms	remaining: 2.91s
195:	learn: 11668.3443105	total: 705ms	remaining: 2.89s
196:	learn: 11645.4413776	total: 706ms	remaining: 2.88s
197:	learn: 11627.2306870	total: 706ms	remaining: 2.86s
198:	learn: 11595.3451456	total: 707ms	remaining: 2.85s
199:	learn: 11575.0763177	total: 708ms	remaining: 2.83s
200:	learn: 11548.3456591	total: 708ms	remaining: 2.81s
201:	learn: 11525.8505273	total: 709ms	remaining: 2.8s
202:	learn: 11509.5479596	total: 709ms	remaining: 2.79s
203:	learn: 11498.0994381	total: 710ms	remaining: 2.77s
204:	learn: 11476.1903327	total: 711ms	remaining: 2.75s
205:	learn: 11461.4224784	total: 711ms	remaining: 2.74s
206:	learn: 11442.5381593	total: 712ms	remaining: 2.73s
207:	learn: 11431.8507239	total: 712ms	remaining: 2.71s
208:	learn: 11411.4095720	total: 713ms	remaining: 2.7s
209:	learn: 11388.5948823	total: 714ms	remaining: 2.68s
210:	learn: 11375.2898740	total: 714ms	remaining: 2.67s
211:	learn: 11368.5648084	total: 715ms	remaining: 2.66s
212:	learn: 11342.6485950	total: 715ms	remaining: 2.64s
213:	learn: 11328.1151065	total: 716ms	remaining: 2.63s
214:	learn: 11314.2659856	total: 716ms	remaining: 2.62s
215:	learn: 11300.2359633	total: 717ms	remaining: 2.6s
216:	learn: 11275.0945723	total: 718ms	remaining: 2.59s
217:	learn: 11268.2842386	total: 718ms	remaining: 2.58s
218:	learn: 11260.1137491	total: 719ms	remaining: 2.56s
219:	learn: 11241.4240595	total: 719ms	remaining: 2.55s
220:	learn: 11212.9921136	total: 720ms	remaining: 2.54s
221:	learn: 11200.6781762	total: 721ms	remaining: 2.52s
222:	learn: 11190.0453028	total: 721ms	remaining: 2.51s
223:	learn: 11169.4864477	total: 722ms	remaining: 2.5s
224:	learn: 11159.0355623	total: 723ms	remaining: 2.49s
225:	learn: 11147.4399909	total: 723ms	remaining: 2.48s
226:	learn: 11140.4138595	total: 724ms	remaining: 2.46s
227:	learn: 11130.3943436	total: 724ms	remaining: 2.45s
228:	learn: 11110.1506879	total: 725ms	remaining: 2.44s
229:	learn: 11099.7976731	total: 725ms	remaining: 2.43s
230:	learn: 11092.4240401	total: 726ms	remaining: 2.42s
231:	learn: 11074.6363878	total: 726ms	remaining: 2.4s
232:	learn: 11052.6772812	total: 727ms	remaining: 2.39s
233:	learn: 11036.6329883	total: 728ms	remaining: 2.38s
234:	learn: 11025.9284550	total: 728ms	remaining: 2.37s
235:	learn: 11019.5512691	total: 729ms	remaining: 2.36s
236:	learn: 11015.5124217	total: 730ms	remaining: 2.35s
237:	learn: 11010.2680294	total: 730ms	remaining: 2.34s
238:	learn: 11004.6603253	total: 731ms	remaining: 2.33s
239:	learn: 10990.6094315	total: 731ms	remaining: 2.31s
240:	learn: 10980.4615790	total: 732ms	remaining: 2.31s
241:	learn: 10962.9116293	total: 732ms	remaining: 2.29s
242:	learn: 10935.6646751	total: 733ms	remaining: 2.28s
243:	learn: 10925.7445783	total: 734ms	remaining: 2.27s
244:	learn: 10916.7946740	total: 734ms	remaining: 2.26s
245:	learn: 10907.0077442	total: 735ms	remaining: 2.25s
246:	learn: 10882.3614723	total: 735ms	remaining: 2.24s
247:	learn: 10872.7029389	total: 736ms	remaining: 2.23s
248:	learn: 10848.2179592	total: 736ms	remaining: 2.22s
249:	learn: 10826.6034769	total: 737ms	remaining: 2.21s
250:	learn: 10813.4880698	total: 737ms	remaining: 2.2s
251:	learn: 10804.4530848	total: 738ms	remaining: 2.19s
252:	learn: 10799.7133774	total: 739ms	remaining: 2.18s
253:	learn: 10781.4412514	total: 739ms	remaining: 2.17s
254:	learn: 10757.6674317	total: 740ms	remaining: 2.16s
255:	learn: 10748.4816291	total: 740ms	remaining: 2.15s
256:	learn: 10739.5333290	total: 741ms	remaining: 2.14s
257:	learn: 10724.9927032	total: 742ms	remaining: 2.13s
258:	learn: 10721.3946256	total: 742ms	remaining: 2.12s
259:	learn: 10705.9352526	total: 743ms	remaining: 2.11s
260:	learn: 10679.0153586	total: 744ms	remaining: 2.1s
261:	learn: 10674.3527563	total: 745ms	remaining: 2.1s
262:	learn: 10654.8203158	total: 752ms	remaining: 2.11s
263:	learn: 10640.5900327	total: 753ms	remaining: 2.1s
264:	learn: 10631.7794800	total: 754ms	remaining: 2.09s
265:	learn: 10623.0284627	total: 754ms	remaining: 2.08s
266:	learn: 10617.8107768	total: 755ms	remaining: 2.07s
267:	learn: 10568.8480478	total: 756ms	remaining: 2.06s
268:	learn: 10551.1005887	total: 756ms	remaining: 2.06s
269:	learn: 10546.4456568	total: 757ms	remaining: 2.05s
270:	learn: 10527.9627929	total: 757ms	remaining: 2.04s
271:	learn: 10504.4304268	total: 758ms	remaining: 2.03s
272:	learn: 10461.3946360	total: 759ms	remaining: 2.02s
273:	learn: 10426.0488555	total: 759ms	remaining: 2.01s
274:	learn: 10405.3234495	total: 760ms	remaining: 2s
275:	learn: 10400.5487504	total: 761ms	remaining: 2s
276:	learn: 10395.6400876	total: 761ms	remaining: 1.99s
277:	learn: 10384.4760295	total: 762ms	remaining: 1.98s
278:	learn: 10376.3592858	total: 763ms	remaining: 1.97s
279:	learn: 10370.5350340	total: 763ms	remaining: 1.96s
280:	learn: 10348.6145000	total: 764ms	remaining: 1.95s
281:	learn: 10337.2791534	total: 764ms	remaining: 1.95s
282:	learn: 10329.5540136	total: 765ms	remaining: 1.94s
283:	learn: 10295.7680077	total: 766ms	remaining: 1.93s
284:	learn: 10290.1319974	total: 766ms	remaining: 1.92s
285:	learn: 10270.4693462	total: 767ms	remaining: 1.91s
286:	learn: 10250.8400040	total: 767ms	remaining: 1.91s
287:	learn: 10239.4432461	total: 768ms	remaining: 1.9s
288:	learn: 10198.5253385	total: 769ms	remaining: 1.89s
289:	learn: 10179.8996767	total: 770ms	remaining: 1.89s
290:	learn: 10148.6587247	total: 776ms	remaining: 1.89s
291:	learn: 10138.9584562	total: 776ms	remaining: 1.88s
292:	learn: 10130.2393435	total: 777ms	remaining: 1.87s
293:	learn: 10117.5145759	total: 777ms	remaining: 1.87s
294:	learn: 10105.7769661	total: 778ms	remaining: 1.86s
295:	learn: 10101.3503334	total: 778ms	remaining: 1.85s
296:	learn: 10077.4767581	total: 779ms	remaining: 1.84s
297:	learn: 10036.1666295	total: 780ms	remaining: 1.84s
298:	learn: 10032.0173465	total: 780ms	remaining: 1.83s
299:	learn: 10027.1301112	total: 781ms	remaining: 1.82s
300:	learn: 9987.1590624	total: 782ms	remaining: 1.81s
301:	learn: 9975.8951782	total: 782ms	remaining: 1.81s
302:	learn: 9972.6847713	total: 783ms	remaining: 1.8s
303:	learn: 9962.3067585	total: 783ms	remaining: 1.79s
304:	learn: 9958.0538956	total: 784ms	remaining: 1.78s
305:	learn: 9928.9407298	total: 784ms	remaining: 1.78s
306:	learn: 9906.3309646	total: 785ms	remaining: 1.77s
307:	learn: 9901.8510824	total: 785ms	remaining: 1.76s
308:	learn: 9886.4760338	total: 786ms	remaining: 1.76s
309:	learn: 9883.7985255	total: 786ms	remaining: 1.75s
310:	learn: 9876.5836110	total: 787ms	remaining: 1.74s
311:	learn: 9860.2422068	total: 788ms	remaining: 1.74s
312:	learn: 9842.2175772	total: 788ms	remaining: 1.73s
313:	learn: 9824.1472281	total: 789ms	remaining: 1.72s
314:	learn: 9821.3203877	total: 789ms	remaining: 1.72s
315:	learn: 9817.7433933	total: 790ms	remaining: 1.71s
316:	learn: 9812.6058841	total: 791ms	remaining: 1.7s
317:	learn: 9779.3125005	total: 791ms	remaining: 1.7s
318:	learn: 9750.1089696	total: 792ms	remaining: 1.69s
319:	learn: 9716.0636922	total: 792ms	remaining: 1.68s
320:	learn: 9680.0831185	total: 793ms	remaining: 1.68s
321:	learn: 9663.0765526	total: 793ms	remaining: 1.67s
322:	learn: 9647.0487597	total: 794ms	remaining: 1.66s
323:	learn: 9639.3168291	total: 795ms	remaining: 1.66s
324:	learn: 9631.6077664	total: 797ms	remaining: 1.65s
325:	learn: 9599.6317088	total: 798ms	remaining: 1.65s
326:	learn: 9596.0398878	total: 799ms	remaining: 1.64s
327:	learn: 9593.2892511	total: 799ms	remaining: 1.64s
328:	learn: 9570.5488741	total: 800ms	remaining: 1.63s
329:	learn: 9561.5871452	total: 801ms	remaining: 1.63s
330:	learn: 9554.1326423	total: 801ms	remaining: 1.62s
331:	learn: 9523.5761812	total: 802ms	remaining: 1.61s
332:	learn: 9494.9131365	total: 802ms	remaining: 1.61s
333:	learn: 9491.9862163	total: 803ms	remaining: 1.6s
334:	learn: 9488.4140454	total: 803ms	remaining: 1.59s
335:	learn: 9480.9471324	total: 804ms	remaining: 1.59s
336:	learn: 9463.1284959	total: 805ms	remaining: 1.58s
337:	learn: 9460.7545489	total: 805ms	remaining: 1.58s
338:	learn: 9445.6476394	total: 806ms	remaining: 1.57s
339:	learn: 9442.3364182	total: 806ms	remaining: 1.56s
340:	learn: 9418.6976216	total: 807ms	remaining: 1.56s
341:	learn: 9415.4364116	total: 807ms	remaining: 1.55s
342:	learn: 9407.8811632	total: 808ms	remaining: 1.55s
343:	learn: 9380.8244906	total: 808ms	remaining: 1.54s
344:	learn: 9359.0622625	total: 809ms	remaining: 1.53s
345:	learn: 9356.9883953	total: 809ms	remaining: 1.53s
346:	learn: 9331.5116895	total: 810ms	remaining: 1.52s
347:	learn: 9319.8821119	total: 811ms	remaining: 1.52s
348:	learn: 9317.6885459	total: 812ms	remaining: 1.51s
349:	learn: 9303.0169715	total: 812ms	remaining: 1.51s
350:	learn: 9267.2062910	total: 813ms	remaining: 1.5s
351:	learn: 9262.2397385	total: 820ms	remaining: 1.51s
352:	learn: 9248.0812182	total: 821ms	remaining: 1.5s
353:	learn: 9230.9349430	total: 822ms	remaining: 1.5s
354:	learn: 9208.5939327	total: 822ms	remaining: 1.49s
355:	learn: 9191.0063984	total: 823ms	remaining: 1.49s
356:	learn: 9184.5094770	total: 823ms	remaining: 1.48s
357:	learn: 9167.8669579	total: 825ms	remaining: 1.48s
358:	learn: 9139.9936623	total: 826ms	remaining: 1.47s
359:	learn: 9120.0859387	total: 826ms	remaining: 1.47s

# Submission 2

In [ ]:
submission = pd.read_csv("/content/drive/MyDrive/DAC 1/submission_format.csv")

In [ ]:
# Latih model XGBoost
model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)
model.fit(x_train,y_train)

# Lakukan prediksi pada data uji
y_pred = model.predict(x_pred_unixversal)

In [ ]:
submission['Price'] = y_pred

In [ ]:
submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      767 non-null    int64
 1   Price   767 non-null    float32
dtypes: float32(1), int64(1)
memory usage: 9.1 KB

In [ ]:
submission

      ID         Price
0      0  62981.464844
1      1  72155.226562
2      2  15093.222656
3      3  72155.226562
4      4  18259.474609
..   ...           ...
762  762  72096.195312
763  763  71887.203125
764  764  72155.226562
765  765  72096.195312
766  766  72155.226562

[767 rows x 2 columns]

In [ ]:
submission.describe()

               ID         Price
count  767.000000    767.000000
mean   383.000000  59686.863281
std    221.558119  22156.126953
min      0.000000  11705.791016
25%    191.500000  62981.464844
50%    383.000000  72096.195312
75%    574.500000  72155.226562
max    766.000000  73947.257812

In [ ]:
submission.to_csv("submission_RF.csv",index = False)

# Submission 1

In [ ]:
submission = pd.read_csv("/content/drive/MyDrive/DAC 1/submission_format.csv")

In [ ]:
forest_model = RandomForestRegressor(random_state=42) #n_estimators is 100 by default
forest_model.fit(x_train, y_train)
forest_model_prediction = forest_model.predict(x_pred_unixversal)

<ipython-input-171-61cb9f097700>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest_model.fit(x_train, y_train)
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(

In [ ]:
submission['Price'] = forest_model_prediction

In [ ]:
submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      767 non-null    int64
 1   Price   767 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 12.1 KB

In [ ]:
submission

      ID    Price
0      0  35804.0
1      1  43664.0
2      2  15800.0
3      3  43664.0
4      4  18530.0
..   ...      ...
762  762  43664.0
763  763  41974.0
764  764  43664.0
765  765  43664.0
766  766  43664.0

[767 rows x 2 columns]

In [ ]:
submission.describe()

               ID         Price
count  767.000000    767.000000
mean   383.000000  37508.170795
std    221.558119  10447.046562
min      0.000000  13553.000000
25%    191.500000  35804.000000
50%    383.000000  43664.000000
75%    574.500000  43664.000000
max    766.000000  44452.000000

In [ ]:
submission.to_csv("submission_RF.csv",index = False)